language: python
dist: xenial
sudo: true
install:
- pip install coverage pytest-cov coveralls
- pip install -r requirements_dev.txt
after_success:
- coveralls
matrix:
  include:
  - name: '3.5'
    python: 3.5
  - name: '3.6'
    python: 3.6
  - name: '3.7'
    python: 3.7
script: pytest --cov=pythx tests/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: dmuhs
  password:
    secure: V/pTTXghh3sf+7fnOM71alcW/zB2VSv4lpAVkpk4WLyN8UOal4ZtcRNsLTsqs8JwjpkR6GjsKTaiDR73YBAOgtjy8XuCrx6wy2yZXUUy2HA1aXW5PJ17uXU5ldpPBVskllrCL1Zfst+WS3r448efu6bxJwd5TyG5ah2G3XqGD2Yzrrjitglbypt7HyUD7oLPA6s+8K+nISjHNIxMW+nK7+ABn8xRwzqio+K8+RyPdVmb9tnDnu1qg6b0IuoGsdO/56Z5ujx5SgHTjqLjc0eHBDBtvy33JP7i3zjFX0K+hJ/ipeFymmeja6MtfoRmgMyZxJoIpF4HZEZFHK9TKM6ENll+J2KphYgZdS5ytcNdVu8fQmtNQjFZCAAXd7ONcwfxR5XfMeB1Khyp90wpbKBjmXDtaYCvAg9/8iiozXwjMHec0CpCIEqx4vPhJ7bEXgQTkwm0X686TByyCYJAsD+zXqQLpBXyXs9dUKLBOcd/TIykj6zubUCVVbx3utsN47PGE2STqzEiZMV7fDX5hMdZiz03z98M9kcsCcgbGLdu+UF6FRGwIbpLBSJxaxH7aSoBadzf2hi00STKarvTspZJmSl1pUdtGIBHzpSgX99jc9WsyZsWFl5Ss/DWA/wwnVA/09dstpUjiNa9P1Di150LookxrAP6igjCwoTM//PzeNE=
  on:
    tags: true
    repo: dmuhs/pythx
    python: 3.6
