language: python
dist: xenial
sudo: true
install:
- pip install coverage pytest-cov coveralls
- pip install -r requirements_dev.txt
after_success:
- coveralls
matrix:
  include:
  - name: '3.6'
    python: 3.6
  - name: '3.7'
    python: 3.7
  - name: '3.8'
    python: 3.8
script: pytest --cov=pythx tests/
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  skip_cleanup: true
  user: dmuhs
  password:
    secure: b6qRz/N6S4PShUOS0hDZoznFBpCt291LA4WzepszCQ7xhNCxI7dmP7+ORoW53JKW7k7NPh0QNjNCuW6IoylTShswxZ4m4X+EuTQfHhccqQ/fVXbUDxvLabzyNbrdHx6LLbu9twJB2j+ZjM7jjYogcDF1tYYVvv8ZykX7l7G9lh/n9Iwgunqh6JvsWmAOfm6/MhgfwObSbwJztMHVakfbjCC0wTe20dLpyZNUHVVy/hS/bJ0+6t2nYI/toWn0FGK6i8PTjbcYT5tEO2oqybnaT5D0Z2h6h3rAMkxxlpd8XmAUP7mnZDzGSZBJfDHZcUPLS2c8nZyCwLXt50ZcFOAFI2i6lIEp9fdEDOyo884GGEz85fLGnzxJ9TyczLiir81+Ufc01D5XvY8c4OYYzSKV/pyzvoHdTvUIPjOQ9eoIvCLO/KOEJ31cbqvpwKCJaRqyh9bd/s0rnV9HNJcWdfBwp4PeMoP4FGmL4ZQAeGyfRnkbIyo/WLX4POswC9nbCHb2AaTQ+RemigZiujslKm2r1eF1vLJUuGQGrhNA7raS51WDU34s7H04L6g3SG48uJpzzqIZbaY4bRNJqXS2fzJVLxhAQDgWxBugjSgpRpZR8oSYZpFqf/bG2wrrecMCrVd626y9r/hgxFlMA8BvRWKz5J6qBoin2zpvXK8NV9GqRRc=
  on:
    tags: true
    repo: dmuhs/pythx
    python: 3.6
